### ISSUE TITLE
Removing GatewayParameters Annotation from Gateway Does Not Propagate Updates

### ISSUE THREAD

**Issue by danehans** [k8sgateway/k8sgateway#10099]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.17.7

### Kubernetes Version

v1.28.0

### Describe the bug

Initially adding the `gateway.gloo.solo.io/gateway-parameters-name: gloo-gateway2 ` annotation to the Gateway caused the managed proxy deployment replicas to be updated properly since gloo-gateway2 is configured with 2 replicas. Removing this annotation or updating the value to `gloo-gateway` (the default) does not cause the managed proxy deployment to revert back to 1 unless I reboot GG.

### Expected Behavior

The managed proxy deployment to be updated with 1 replica.

### Steps to reproduce the bug

1. Setup GGv2 using the quick start [guide](https://docs.solo.io/gateway/latest/quickstart/).
2. Create a new GatewayParameters with all the same configuration as the default GatewayParameters except change replicas from 1 to 2.
3. Update the Gateway to reference the new GatewayParameters by applying the `gateway.gloo.solo.io/gateway-parameters-name` annotation.
4. Observe the number of replicas for the managed Envoy deployment.
5. Remove the the annotation.
6. Observe the number of replicas for the managed Envoy deployment.

### Additional Environment Detail

I used the `ci/kind/setup-kind.sh` script to setup the cluster, load gloo images, etc.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1207635280052738/1208391610128313) by [Unito](https://www.unito.io)

**Comment by danehans** [comment]
The `gateway.gloo.solo.io/gateway-parameters-name` annotation should be deprecated when GGv2 supports Gateway API v1.1.0 in favor of [GatewayInfrastructure](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.GatewayInfrastructure) `parametersRef`.

**Comment by timflannagan** [comment]
Should we back this to 1.17.x too?

**Comment by danehans** [comment]
@timflannagan yes we should. I'll create a tracker issue on Monday unless someone else beats me to it.

**Comment by nfuden** [comment]
Since we are backporting lets reopen and reassign if someone else needs to take this over the line

**Comment by danehans** [comment]
I was unsure of the backport process so I created https://github.com/solo-io/gloo/issues/10185 for the backport. I'll close https://github.com/solo-io/gloo/issues/10185 since this was reopened.

**Comment by danehans** [comment]
Fixed by https://github.com/k8sgateway/k8sgateway/pull/10107.
