### ISSUE TITLE
External processor in response headers flow

### ISSUE THREAD

**Issue by DreyfussDaena** [k8sgateway/k8sgateway#10241]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

gloo-ee-1.17.x

### Kubernetes Version

v1.28.6

### Describe the bug

Hi Solo Team,
We’d like to open a ticket regarding an issue we’re experiencing with the response headers flow in the external processor.
To support the Response Headers Flow, we’ve set responseHeaderMode to SEND in the global Settings resource. 
While this setting does translate correctly to Envoy in the config dump, we are not receiving any response header requests. 

Strangely, we do receive these response headers requests when we set requestHeaderMode to SKIP, but our intent is to support both.

We’ve set the log level to info on all loggers and couldn’t find any issues in the logs, and after changing to the global settings resource we restarted the Gloo pod.
Additionally, we know this configuration worked for us previously, as we had supported it earlier and only skipped it when it was no longer required. But it was when we used the forked version on earlier Gloo-ee versions (could be 1.16.x or even 1.15.x).
Could you assist in investigating this issue? 

### Expected Behavior

When responseHeaderMode is set to SEND, we should receive response headers requests.

### Steps to reproduce the bug

Set responseHeaderMode to SEND in global Settings resource
Check response headers

### Additional Environment Detail

Additionally, we know this configuration worked for us previously, as we had supported it earlier and only skipped it when it was no longer required. But it was when we used the forked version on earlier Gloo-ee versions (could be 1.16.x or even 1.15.x).
Could you assist in investigating this issue? 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206681874205238/1208660692848530) by [Unito](https://www.unito.io)

**Comment by nfuden** [comment]
As part of this we should update https://github.com/solo-io/ext-proc-examples/blob/main/basic-sink/go.mod#L8 to use a golang commensurate with Gateway 1.17 and also update gRPC to google.golang.org/grpc v1.66.2

**Comment by DreyfussDaena** [comment]
Hey @nfuden @DuncanDoyle 
Could we have an estimation regarding this issue?
Thanks a lot,
Daena
