### ISSUE TITLE
Add test coverage statistics to gloo

### ISSUE THREAD

**Issue by sheidkamp** [k8sgateway/k8sgateway#7801]
### Version

1.14.x (beta)

### Is your feature request related to a problem? Please describe.

Problem: We currently do not regularly track test coverage.

### Describe the solution you'd like

Use existing github tools and libraries to calculate the extent of our test coverage (ideally as a top level % with the ability to drill down to the file/line level) and display the results as part of the pipeline results. Possibly also add a github badge.

**Comment by nfuden** [comment]
This is already planned in stability initiative to some extent. kube2e test exercise alot that many coverage analyzers with throw out btw
