### ISSUE TITLE
Support external redis for rate-limiting with client side sharding

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#7813]
### Gloo Edge Version

1.12.x

### Kubernetes Version

None

### Describe the bug

Unable to modify the redis address used in the sharding `rate-limit-sidecar-config` configmap via helm which prevents combining sharding with an external redis. 

### Steps to reproduce the bug

1. Install GE with `redis.clientSideShardingEnabled: true` and` redis.service` pointed to an external service. 
2. The `rate-limit-sidecar-config` configmap will still be configured with `redis:6349`

### Expected Behavior

Able to install with sharding and an external redis address

**Comment by jackstine** [comment]
[Here is some information on the unix socket for the redis configuration.](https://github.com/solo-io/solo-projects/blob/master/install/helm/gloo-ee/templates/25-rate-limit-sidecar-config-and-redis-secret.yaml#L91)

**Comment by bdecoste** [comment]
This isn't a unix socket issue. Helm will not let you configure both client-side sharding and use an external redis
