### ISSUE TITLE
Okta OIDC - without a refresh token, when the access and id tokens are both expired a 500 is returned 

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#7861]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

None

### Describe the bug

When using Okta OIDC without a refresh token, when the access and id tokens are both expired request will return a 500. The request should be redirected back the IdP login page. 

### Steps to reproduce the bug

1. Configure Okta OIDC with allowRefreshing false
2. Configure Okta so that the expiration of the access token < expiration of id token (60 mins)
3. Send a request and go through the OIDC flow. 
4. Wait 1 hour until the id token expires and send another request 
5. A 500 is returned. This should redirect to the Okta login page

### Expected Behavior

When there is no refresh token and the access and id tokens are expired a request should redirect to the Okta login page

**Comment by edubonifs** [comment]
Also drdropin-soloio asking for this
