### ISSUE TITLE
Investigate using project agnostic terminology in the AuthConfig API

### ISSUE THREAD

**Issue by timflannagan** [k8sgateway/k8sgateway#7899]
### Version

None

### Is your feature request related to a problem? Please describe.

We currently make explicit references to the "Gloo Edge" project throughout the AuthConfig API documentation, and this API is also being consumed by the Gloo Platform product. This can lead to a confusing UX when enterprise users see references to the "Gloo Edge" project or "Gloo Edge Enterprise" product in the Gloo Platform API documentation.

### Describe the solution you'd like

Consider updating the documented terminology to be product/project agnostic.

### Describe alternatives you've considered

N/A.

### Additional Context

See https://github.com/solo-io/gloo-mesh-enterprise/pull/7602#discussion_r1107838308 for more context on this overall ask.

**Comment by timflannagan** [comment]
cc @sam-heilbron @marcogschmidt

**Comment by nfuden** [comment]
@marcogschmidt as you are tagged in this we should discuss what subsection of the protos are intended to be consumed (is it just rate limit and ext auth?) to correctly scope this
