### ISSUE TITLE
HCM overrides do not support 0-value overrides

### ISSUE THREAD

**Issue by Ati59** [k8sgateway/k8sgateway#7982]
### Gloo Edge Version

1.13.x (beta)

### Kubernetes Version

None

### Describe the bug

The issue when using HttpConnectionManagerSettings_CodecType  = 0 still appears.

Seems that the type of HttpConnectionManagerSettings_CodecType is int32, instead of *int32

This is a bug already faced, see original feature bug : https://github.com/solo-io/gloo/issues/6476

### Steps to reproduce the bug

See https://github.com/solo-io/gloo/issues/6476

### Expected Behavior

The override should working.

**Comment by avizov** [comment]
@Ati59 , the gloo edge version is 1.13.x (1.13.12)
