### ISSUE TITLE
Error applying new CRDs when preserveUnknownFields is true

### ISSUE THREAD

**Issue by jenshu** [k8sgateway/k8sgateway#8018]
### Gloo Edge Version

1.14.x (beta)

### Kubernetes Version

None

### Describe the bug

Some customers have encountered errors applying the latest Gloo Edge CRDs, with an error message like `spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema`. This happens if Gloo Edge was originally installed with a version from before we added openapi schemas in the CRDs.

When we first [introduced openapi validation schemas](https://github.com/solo-io/gloo/pull/4757/), we correctly had set preserveUnknownFields to false. But when we upgraded to `apiextensions.k8s.io/v1` CRDs (see [solo-kit PR](https://github.com/solo-io/solo-kit/pull/451) and associated [gloo PR](https://github.com/solo-io/gloo/pull/5373)), we removed the preserveUnknownFields=false, with the assumption that we no longer needed to set that field explicitly since it was the new default. This line was removed from ApplyValidationSchemaToCRD:
```
	// Setting PreserveUnknownFields to false ensures that objects with unknown fields are rejected.
	// This is deprecated and will default to false in future versions.
	crd.Spec.PreserveUnknownFields = pointer.BoolPtr(false)
```
However this did not take into account that upgrades from older Gloo Edge / CRD versions may have this field set to true, and we would need to explicitly override it. See [CRD field pruning](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning) for more info.

To fix, we should add back those lines in the solo-kit crd generation code to explicitly set preserveUnknownFields to false.

### Steps to reproduce the bug

```
# create cluster on k8s 1.21 (apiextensions.k8s.io/v1beta1 CustomResourceDefinition was removed in k8s 1.22+)
kind create cluster --name test --image "kindest/node:v1.21.1"

# install a version of gloo from before openapi schemas were added
helm install -n gloo-system gloo gloo/gloo --create-namespace --version 1.8.0-beta15

# see that spec.preserveUnknownFields is set to true by default
kubectl get crd upstreams.gloo.solo.io -oyaml

# upgrade to a newer version of Gloo Edge that uses defaults in the schema
helm pull gloo/gloo --version 1.13.0 --untar
kubectl apply -f gloo/crds
```

The apply will fail with: `error when patching "gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml": CustomResourceDefinition.apiextensions.k8s.io "upstreamgroups.gloo.solo.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema`

### Expected Behavior

CRDs should apply successfully

### Additional Context

We should backport to all LTS branches

**Comment by RaphaelKellerAdc** [comment]
Our customers also faced this issue while upgrading.

**Comment by pseudonator** [comment]
One of the customers faced this when upgrading from `1.9.1` to `1.14.8`.
Interim fix was to manually update all the CRDs with `spec.preserveUnknownFields=false` before proceeding with the upgrade.
