### ISSUE TITLE
Support client credentials flow

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#8020]
### Version

1.13.x (latest stable)

### Is your feature request related to a problem? Please describe.

We require support for the OIDC client credentials flow. Gloo currently only supports the auth code flow

### Describe the solution you'd like

Support the OIDC client credentials flow

### Describe alternatives you've considered

Auth code flow

**Comment by jackstine** [comment]
https://www.rfc-editor.org/rfc/rfc6749#section-4.4

**Comment by bdecoste** [comment]
We currently only support the authorization code grant, the user has requested that we also supposed the client credientials grant
