### ISSUE TITLE
Push proxy resource to in-memory config

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#8034]
### Version

1.13.x (latest stable)

### Is your feature request related to a problem? Please describe.

Prior to 1.12 the proxy resource was always represented as a CR so we were able to quickly and easily replicate the config from one env to another by deploying the proxy CR. In 1.12+ in order to take advantage of the performance improvements by moving the proxy resource from a CR to in-memory we lost the ability to replicate the config. 

### Describe the solution you'd like

Ability to push a proxy resource to the in-memory state via an API

### Describe alternatives you've considered

Lose the performance benefits of the in-memory proxy and go back to using CRs

**Comment by nfuden** [comment]
Is this intended to give a starting resource standpoint? Whats the gap with regards to glooctl proxy served-config? Is the format wrong or that it cant be loaded as a bootstrap?

**Comment by bdecoste** [comment]
Yes, the request is to be able to load a full 1.11-style `proxies.gloo.solo.io` resource. In 1.11 they could just recreate the proxy resource

**Comment by sam-heilbron** [comment]
Slack context: https://solo-io-corp.slack.com/archives/C0289JZGV8R/p1691759616117229
