### ISSUE TITLE
insync and outofsync xds stats are not always consistent 

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#8038]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

None

### Describe the bug

`glooe_solo_io_xds_insync` and `glooe_solo_io_xds_outofsync` gloo pod metrics do not always align

### Steps to reproduce the bug

Add the following to the bootstrap `gateway-proxy-envoy-config` configmap for the `gloo.gloo-system.svc.cluster.local:9977` cluster:

```
        common_http_protocol_options:
          max_stream_duration: 1s
```

Port-forward gloo pod 9091 and track the following. The `insync` stats will toggle but will not always match the `outofsync`:

```
$ curl -s http://localhost:9091/metrics | grep xds | grep sync
# HELP glooe_solo_io_xds_insync The envoys that are in sync
# TYPE glooe_solo_io_xds_insync counter
glooe_solo_io_xds_insync{resource="type.googleapis.com/enterprise.gloo.solo.io.ExtAuthConfig"} 1
glooe_solo_io_xds_insync{resource="type.googleapis.com/envoy.config.cluster.v3.Cluster"} 0
glooe_solo_io_xds_insync{resource="type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment"} 0
glooe_solo_io_xds_insync{resource="type.googleapis.com/envoy.config.listener.v3.Listener"} 0
glooe_solo_io_xds_insync{resource="type.googleapis.com/envoy.config.route.v3.RouteConfiguration"} 0
glooe_solo_io_xds_insync{resource="type.googleapis.com/glooe.solo.io.RateLimitConfig"} 1

```

### Expected Behavior

`insync` and `outofsync` stats are consistent

**Comment by sam-heilbron** [comment]
Additional context in: https://github.com/solo-io/solo-projects/issues/4461
