### ISSUE TITLE
ExtAuth API keys external storage clients fail to initialize

### ISSUE THREAD

**Issue by jbohanon** [k8sgateway/k8sgateway#8045]
### Description

If an ExtAuth APIKeys AuthService is configured with external storage, the service is not resilient to network issues. If a client fails to connect initially, the AuthService will remain in a useless state until the pod is restarted

### Steps to reproduce the bug

1. Install Gloo Edge Enterprise
2. Create AuthConfig with connection details to an Aerospike server **that cannot be reached yet** ([API docs here](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#aerospikeapikeystorage))
4. Check the ExtAuth logs for errors in starting the auth service
5. Make the Aerospike reachable (via firewall rules or by simply waiting to spin up Aerospike until this time)
6. See that connection is not formed

### Expected Behavior

ExtAuth should connect to the configured external storage when it becomes available, and should reconnect in the event of network failure.

### Additional Context

https://github.com/solo-io/ext-auth-service/issues/500

**Comment by nfuden** [comment]
This is not limited to aerospike or apikeys.
