### ISSUE TITLE
Support staged GrpcJsonTranscoder

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#8137]
### Version

1.13.x (latest stable)

### Is your feature request related to a problem? Please describe.

We are implementing gRPC transcoding plus extauth and we want to configure our route matchers using the post-transcoding paths. This is not currently possible as extauth occurs before transcoding. 

### Describe the solution you'd like

Support a staged transcoding filter where transcoding can occur prior to extauth 

### Describe alternatives you've considered

Use original request path routes

**Comment by elcasteel** [comment]
does this need to be backported to 1.13? Also how is the grpc json transcoding being configured?

**Comment by bdecoste** [comment]
The proto is defined on the Upstream.
