### ISSUE TITLE
start with docker-compose-consul, use curl request return  "Empty reply from server"

### ISSUE THREAD

**Issue by nobject** [k8sgateway/k8sgateway#8197]
### Version

master

### Describe the requested changes

https://docs.solo.io/gloo-edge/latest/installation/gateway/development/docker-compose-consul/

start with docker-compose-consul, according to the tutorial above link, there was no response received when sending a request using curl.

result:  curl: (52) Empty reply from server

are you no longer maintaining support for non-Kubernetes enviroment API gateways?  The examples in the basic usage section of the documentation cannot be executed correctly, and the documentation for more features is also mostly based on Kubernetes environment as reference

**Comment by LuisMalhadas** [comment]
second that.
