### ISSUE TITLE
Expose Envoy's scheme_header_transformation, append_x_forwarded_host, append_x_forwarded_port in Gloo API

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#8417]
### Version

None

### Is your feature request related to a problem? Please describe.

Need to be able to control the `:scheme`,~~`x-forwarded-host`~~, and ~~`x-forwarded-port`~~ headers in Envoy 

### Describe the solution you'd like

Expose Envoy's `scheme_header_transformation`, ~~`append_x_forwarded_host`~~, ~~`append_x_forwarded_port`~~ in Gloo API

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-append-x-forwarded-host

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-append-x-forwarded-host

**Comment by totallyGreg** [comment]
Related to https://github.com/solo-io/gloo/issues/7683
