### ISSUE TITLE
Expose initial_metadata in opentelemetryConfig

### ISSUE THREAD

**Issue by huzlak** [k8sgateway/k8sgateway#8494]
### Version

None

### Is your feature request related to a problem? Please describe.

I want to use in-house replacement for otel collector to forward data to backend. To do that, I need to include `Authorization` header in the tracing requests to the collector. Gloo currently [doesn't support](https://docs.solo.io/gloo-edge/main/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/trace/v3/opentelemetry.proto.sk/) this.

### Describe the solution you'd like

I'd like to be able to specify [initial_metadata](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice) in opentelemetryConfig.

### Describe alternatives you've considered

Using otel collector as a "middle-man" to add the header which seems like too much overhead considering envoy's capability to do this.

**Comment by guydc** [comment]
[initial_metadata](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice) is documented as being used for auth: `This can be used for scenarios in which additional ad hoc authorization headers (e.g. x-foo-bar: baz-key) are to be injected.` 

So, I think that it makes sense to support some sort of secret reference mechanism here. For example, something similar to secret header addition in the header manipulation feature: https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/append_remove_headers/
