### ISSUE TITLE
failed creating base settings resource client

### ISSUE THREAD

**Issue by TomerJLevy** [k8sgateway/k8sgateway#8612]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.14.4

### Kubernetes Version

v1.25.11

### Describe the bug

Gloo pod restarted 3 times within several minutes due to some network issue
The pod logged this:

> "Wed, 23 Aug 2023 12:20:37 UTC: github.com/solo-io/solo-projects/projects/gloo/cmd/main.go:17"	err in main: "creating base Settings resource client: list check failed: Get \"https://<cluster-address>:443/apis/gloo.solo.io/v1/namespaces/apigw-gloo-ee/settings\": read TCP ... read: connection reset by peer - error from a previous attempt: read TCP ... read: connection reset by peer"

Might be related to this open issue https://github.com/solo-io/gloo/issues/8107

### Expected Behavior

If it makes sense maybe the Gloo pod should have some retry mechanism to try and create that client

### Steps to reproduce the bug

I am unsure how to reproduce the bug, we experienced some issues with the API server during that timeframe. I guess if you're able to cause an issue with the API server it might reproduced

**Comment by avizov** [comment]
It probably relates to same issue that reported here https://github.com/solo-io/gloo/issues/8107

**Comment by nfuden** [comment]
After some internal discussion we have come up with the following ideas:

1. We still want to maintain the ability for a microservice to mark itself as being unhealthy and start the process of its cleanup
2. We want to allow users to decide how their budget of how potentially long the control plane could be wrong. 

While we should do a deeper dive on our fully erroring versus marking unhealthy habits we believe that minimally it makes sense to support configurable retries on our shared informers(which uses the kubernetes api)
