### ISSUE TITLE
Add ability to configure json envoy logs

### ISSUE THREAD

**Issue by kevin-shelaga** [k8sgateway/k8sgateway#8729]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.14.x

### Is your feature request related to a problem? Please describe.

Customer would like to have envoy debug logging configured as json

https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/application_logging#printing-logs-in-json-format

### Describe the solution you'd like

helm flag to configure bootstrap cm

### Describe alternatives you've considered

manually configure json logging

**Comment by marckamerbeek** [comment]
Please use this to get all the logging in json until this issue is implemented:
`gloo:
  gatewayProxies:
    <NAME_OF_PROXY>:
      extraEnvoyArgs:
        - --log-format {"timestamp":"%Y-%m-%dT%T.%F","threadId":"%t","level":"%l","message":"%j","source":"envoy"}
      gatewaySettings:
        accessLoggingService:
          accessLog:
            - fileSink:
                path: /dev/stdout
                jsonFormat:
                  source: "access-logs"
                  protocol: "%PROTOCOL%"
                  duration: "%DURATION%"
                  upstreamCluster: "%UPSTREAM_CLUSTER%"
                  upstreamHost: "%UPSTREAM_HOST%"
                  upstreamLocalAddress: "%UPSTREAM_LOCAL_ADDRESS%"
                  upstreamTransportFailureReason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
                  downstreamRemoteAddress: "%DOWNSTREAM_REMOTE_ADDRESS%"
                  downstreamLocalAddress: "%DOWNSTREAM_LOCAL_ADDRESS%"
                  responseDuration: "%RESPONSE_DURATION%"
                  responseFlags: "%RESPONSE_FLAGS%"
                  responseTxDuration: "%RESPONSE_TX_DURATION%"
                  startTime: "%START_TIME(%Y-%m-%dT%H:%M:%S%z %s)%"
                  bytesReceived: "%BYTES_RECEIVED%"
                  responseCode: "%RESPONSE_CODE%"
                  bytesSent: "%BYTES_SENT%"`
