### ISSUE TITLE
Add the possibility of disabling gateway-proxy service creation from the helm chart

### ISSUE THREAD

**Issue by edubonifs** [k8sgateway/k8sgateway#8883]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

The customer creates services “by hand” to expose the gateway listeners (that will be mapped to the ALBs), thus they want an option to disable gateway-proxy service creation but still maintain the gateway-proxy deployments created.

### Describe the solution you'd like

Expose the following field in the helm chart:
gloo.gatewayProxies.gatewayProxy.service.enabled

**Comment by korjek** [comment]
we are also interested in this feature. 
`Gateway` object creates `Service` object with type `LoadBalancer` and as a result AWS LBC creates NLB. But if we want to use ALB instead, we'd create `Ingress` object with `type: alb` so LBC creates ALB. But NLB is still there. Actually two LB are created in this case.
