### ISSUE TITLE
Unable to set the grpc server max_recv_size to a value greater than the default 4MB

### ISSUE THREAD

**Issue by davidjumani** [k8sgateway/k8sgateway#8943]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.16.0

### Kubernetes Version

Any

### Describe the bug

Users ran into this bug when there's a large number of ingresses being translated to xds configurations. The default grpc server max_recv_size is 4MB, which is too small for the large number of ingresses. This bug fixes allows users to set the grpc server max_recv_size to a value greater than 4MB.

### Expected Behavior

Users should be able to set the grpc server max_recv_size to a value greater than 4MB.

### Steps to reproduce the bug

Set settings.gateway.validation.validationServerGrpcMaxSizeBytes to a custom value
The control plane does not honour this value

**Comment by sam-heilbron** [comment]
A review of this issue/resolution can be found here: https://github.com/solo-io/gloo/pull/8875#pullrequestreview-1777573181. To this point, I'm not yet convinced this needs to be solved, though I would happily learn otherwise
